name: zebra
description: Pacote para facilitar a integração entre o Flutter e o TC21 do fornecedor Zebra
version: 1.0.7
homepage:

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.com.srssistemas.zebra
        pluginClass: ZebraPlugin
        